
# Deploy Infrastructure via Terraform
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: 'Deploy Locust headless'

on:
  workflow_dispatch:
    inputs:
      numberOfWorkerNodes:
        description: 'Number of Locust worker nodes (0 stops master)'
        required: true
        default: '0'
      locustRunTime:
        description: 'Duration in Minutes'
        required: true
        default: '15'
      locustSpawnRate:
        description: 'The rate per second in which users are spawned.'
        required: true
        default: '10'
      locustNumUsers:
        description: 'Number of concurrent Locust users.'
        required: true
        default: '100'
      locustTargetUrl:
        description: 'Locust target URL.'
        required: true
        default: 'https://my-sample-web.app'
      envPrefix:
        description: 'environment prefix must not contain any special characters. Must not be longer than 10 characters. Must be all lowercase'
        required: true
        default: 'headless'

defaults:
  run:
    working-directory: 'src/headless/infra'

env:
  ARM_CLIENT_ID:       ${{secrets.TF_ARM_CLIENT_ID}}
  ARM_CLIENT_SECRET:   ${{secrets.TF_ARM_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.TF_ARM_SUBSCRIPTION_ID}}
  ARM_TENANT_ID:       ${{secrets.TF_ARM_TENANT_ID}}
  locustSpawnRate:     ${{github.event.inputs.locustSpawnRate}}
  locustRunTime:       ${{github.event.inputs.locustRunTime}}
  locustNumUsers:      ${{github.event.inputs.locustNumUsers}}
  locustWorkerNodes:   ${{github.event.inputs.numberOfWorkerNodes}}
  locustTargetUrl:     ${{github.event.inputs.locustTargetUrl}}
  PREFIX:              ${{github.event.inputs.envPrefix}} # must not contain any special characters. Must not be longer than 10 characters.

jobs:

  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -list -diff #-check 
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init -backend-config="resource_group_name=${{secrets.TF_BACKEND_RESOURCE_GROUP_NAME}}" -backend-config="storage_account_name=${{secrets.TF_STORAGE_ACCOUNT_NAME}}" -backend-config="container_name=${{secrets.TF_STORAGE_CONTAINER_NAME}}" -backend-config="key=githubaction.locust.headless.$PREFIX.tfstate"

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -input=false -out=tf_plan -var "locustSpawnRate=$locustSpawnRate" -var "locustRunTime=$locustRunTime" -var "locustNumUsers=$locustNumUsers" -var "locustTargetUrl=$locustTargetUrl" -var "prefix=$PREFIX" -var="locustWorkerNodes=$locustWorkerNodes"
      continue-on-error: false

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve tf_plan
      continue-on-error: false

    - name: Sleep for ${{github.event.inputs.locustRunTime}} minutes
      uses: jakejarvis/wait-action@master
      with:
        time: '${{github.event.inputs.locustRunTime+1}}m'

    - name: "Terraform Plan - scale down"
      id: plan-scale-down
      run: terraform plan -input=false -out=tf_plan -var "locustSpawnRate=$locustSpawnRate" -var "locustRunTime=$locustRunTime" -var "locustNumUsers=$locustNumUsers" -var "locustTargetUrl=$locustTargetUrl" -var "prefix=$PREFIX" -var="locustWorkerNodes=0"
      continue-on-error: false

    - name: "Terraform Apply - scale down"
      id: apply-scale-down
      run: terraform apply -auto-approve tf_plan
      continue-on-error: false